# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: M. Duncan • Designer, Web Developer, Small Business Owner 
email: michael@mduncan.me
description: "I'm M. Duncan: a Designer, Web Developer, and Small Business Owner"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mduncan.me" # the base hostname & protocol for your site
twitter_username: _mlduncan
github_username:  ulyth1um
permalink: :title

# Build settings
markdown: kramdown


